export const categories = [
  'All Categories',
  'Boston',
  'California',
  'Chicago',
  'Denver',
  'Florida',
  'greenwich',
  'homepage featured',
  'Los Angeles',
  'Miami',
  'New Jersey',
  'New York',
  'North Carolina',
  'Pennsylvania',
  'Texas',
  'United Kingdom',
];

export const cities = [
  'All Cities',
  'Boston',
  'California',
  'San Diego',
  'Charlotte',
  'chicago',
  'Colorado',
  'Dallas',
  'Florida',
  'Illinois',
  'London',
  'New Jersey',
  'New York',
  'North Carolina',
  'Philadelphia',
  'San Fernando',
  'Shelby',
  'Springfield',
  'Stamford',
  'Texas',
];
